name: convert
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 ffigen: ^2.4.2
 ffi: ^1.0.0

 
dev_dependencies:
  pdf: 3.3.0
  image: ^3.0.2


# ffigen:
#   name: Printing
#   description: Bindings to `include/fpdfview.h`.
#   output: 'lib/src/generated_bindings.dart'
#   headers:
#     entry-points:
#       - 'include/fpdfview.h'